[build]
    base = "/"
    publish = "public/"
    command = "gatsby build"
    functions = "functions/"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
