[build]
    base = "/"
    command = "gatsby build"
    functions = "functions/"
    publish = "public/"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"

[[plugins]]
    package = "netlify-plugin-gatsby-cache"
