name: Lighthouse

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Audit URLs using Lighthouse
      uses: treosh/lighthouse-ci-action@v3
      with:
        urls: |
          https://multei.com.br
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: lighthouseresults
        path: .lighthouseci
